// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqpoj8_QiColqEIcVoEj8Fll61NynYzyg',
    appId: '1:522991040005:web:cdbc2212f5d17399318e6c',
    messagingSenderId: '522991040005',
    projectId: 'shape-log-app',
    authDomain: 'shape-log-app.firebaseapp.com',
    storageBucket: 'shape-log-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaCMdyMn41RENzY9dMsz4HMWHfVljRkWc',
    appId: '1:522991040005:android:720eed548548cde7318e6c',
    messagingSenderId: '522991040005',
    projectId: 'shape-log-app',
    storageBucket: 'shape-log-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB30XjxsQA6KagftNzlQKRvAAg8LrCMACc',
    appId: '1:522991040005:ios:83079a15b15fec6a318e6c',
    messagingSenderId: '522991040005',
    projectId: 'shape-log-app',
    storageBucket: 'shape-log-app.firebasestorage.app',
    iosBundleId: 'com.joaopaulo.shapelog.app',
  );
}
